export const CREATE_NEW_DEAL_REQUEST = "CREATE_NEW_DEAL_REQUEST";
export const CREATE_NEW_DEAL_SUCCESS = "CREATE_NEW_DEAL_SUCCESS";
export const CREATE_NEW_DEAL_FAIL = "CREATE_NEW_DEAL_FAIL";

export const GET_ALL_DEALS_REQUEST = "GET_ALL_DEALS_REQUEST";
export const GET_ALL_DEALS_SUCCESS = "GET_ALL_DEALS_SUCCESS";
export const GET_ALL_DEALS_FAIL = "GET_ALL_DEALS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
