export const CREATE_FEED_REQUEST = "CREATE_FEED_REQUEST";
export const CREATE_FEED_SUCCESS = "CREATE_FEED_SUCCESS";
export const CREATE_FEED_FAIL = "CREATE_FEED_FAIL";

export const DELETE_FEED_REQUEST = "DELETE_FEED_REQUEST";
export const DELETE_FEED_SUCCESS = "DELETE_FEED_SUCCESS";
export const DELETE_FEED_FAIL = "DELETE_FEED_FAIL";

export const GET_ALL_FEEDS_REQUEST = "GET_ALL_FEEDS_REQUEST";
export const GET_ALL_FEEDS_SUCCESS = "GET_ALL_FEEDS_SUCCESS";
export const GET_ALL_FEEDS_FAIL = "GET_ALL_FEEDS_FAIL";

export const GET_ALL_MY_FEEDS_REQUEST = "GET_ALL_MY_FEEDS_REQUEST";
export const GET_ALL_MY_FEEDS_SUCCESS = "GET_ALL_MY_FEEDS_SUCCESS";
export const GET_ALL_MY_FEEDS_FAIL = "GET_ALL_MY_FEEDS_FAIL";

export const GET_FOLLOWINGS_FEEDS_REQUEST = "GET_FOLLOWINGS_FEEDS_REQUEST";
export const GET_FOLLOWINGS_FEEDS_SUCCESS = "GET_FOLLOWINGS_FEEDS_SUCCESS";
export const GET_FOLLOWINGS_FEEDS_FAIL = "GET_FOLLOWINGS_FEEDS_FAIL";

export const MANAGE_FAVORITE_LIST_REQUEST = "MANAGE_FAVORITE_LIST_REQUEST";
export const MANAGE_FAVORITE_LIST_SUCCESS = "MANAGE_FAVORITE_LIST_SUCCESS";
export const MANAGE_FAVORITE_LIST_FAIL = "MANAGE_FAVORITE_LIST_FAIL";

export const GET_FAVORITE_FEEDS_REQUEST = "GET_FAVORITE_FEEDS_REQUEST";
export const GET_FAVORITE_FEEDS_SUCCESS = "GET_FAVORITE_FEEDS_SUCCESS";
export const GET_FAVORITE_FEEDS_FAIL = "GET_FAVORITE_FEEDS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
